title: "Ashikuzzaman - Academic Portfolio"

email: your-email@example.com
description: >-
  Aspiring researcher and developer passionate about technology, innovation, and making an impact.
baseurl: ""
url: "https://ashikuzzaman026.github.io"
theme: minima
minima:
  skin: auto
  include_css:
    - /assets/css/sidebar.css
    - /assets/css/custom-cards.css
